# Generated by Django 3.1.3 on 2020-11-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='groups',
            new_name='group',
        ),
    ]
